//Preferences
export const PREFERENCES_USUARIO = 'PREFERENCES_USUARIO';
export const PREFERENCES_USUARIO_SENHA = 'PREFERENCES_USUARIO_SENHA';
export const PREFERENCES_USUARIO_ID = 'PREFERENCES_USUARIO_ID';
export const PREFERENCES_USUARIO_CIDADE_ID = 'PREFERENCES_USUARIO_CIDADE_ID';
export const PREFERENCES_USUARIO_JSON = 'PREFERENCES_USUARIO_JSON';
export const PREFERENCES_ESCALA_DATAS_MANUAL = 'PREFERENCES_ESCALA_DATAS_MANUAL';
//Endpoints
export const ENPOINT_LOGIN = 'login.php';
export const ENPOINT_GET_CIDADES = 'cidades';
export const ENPOINT_GET_AUDIENCIAS = 'audiencias';
export const ENPOINT_GET_COMUNICADOS = 'comunicados';
export const ENPOINT_GET_ESCALAS = 'escala/get';
export const ENPOINT_GET_TIPOS = 'escala/tipo';
export const ENPOINT_GET_HORARIO = 'escala/horario';
export const ENPOINT_SET_ESCALAS = 'escala/set';
export const ENPOINT_BUILD_ESCALAS = 'escala/build';
export const ENPOINT_GET_GUARDA = 'guarda/get';
export const ENPOINT_SET_GUARDA = 'guarda/set';
export const ENPOINT_SET_CONFIG_GUARDA = 'guarda/config';
//Padrões de data
export const PATTERN_DATE_TIME = 'YYYY-MM-DD';
export const PATTERN_DATE_TIME_FULL = 'YYYY-MM-DD HH:mm:ss';
export const PATTERN_DATE_TIME_UNIX_TIMESTAMP = 'x';
export const PATTERN_DATE_TIME_BR = 'DD/MM/YYYY';
export const PATTERN_DATE_TIME_FULL_BR = 'DD/MM/YYYY HH:mm:ss';
export const PATTERN_DATE_MATH_DAYS = 'days';
export const PATTERN_DATE_MATH_HOURS = 'hours';
export const PATTERN_DATE_MATH_SECONDS = 'seconds';
export const PATTERN_DATE_MATH_MONTHS = 'months';
export const PATTERN_DATE_MATH_YEARS = 'years';
//Autenticacao
export const AUTENTICACAO_PROGRESSO_VIEW = 'AUTENTICACAO_PROGRESSO_VIEW';
export const AUTENTICACAO_LOGIN_SUCESSO = 'AUTENTICACAO_LOGIN_SUCESSO';
export const AUTENTICACAO_LOGIN_ERRO = 'AUTENTICACAO_LOGIN_ERRO';
export const AUTENTICACAO_LOGIN_PROGRESSO = 'AUTENTICACAO_LOGIN_PROGRESSO';
export const AUTENTICACAO_SET_USUARIO = 'AUTENTICACAO_SET_USUARIO';
export const AUTENTICACAO_SET_SENHA = 'AUTENTICACAO_SET_SENHA';
export const AUTENTICACAO_SET_CIDADE = 'AUTENTICACAO_SET_CIDADE';
export const AUTENTICACAO_CIDADES = 'AUTENTICACAO_CIDADES';
export const AUTENTICACAO_CIDADES_LOAD = 'AUTENTICACAO_CIDADES_LOAD';
export const AUTENTICACAO_CIDADES_ERROR = 'AUTENTICACAO_CIDADES_ERROR';
//Comunicados
export const COMUNICADOS_LISTA = 'COMUNICADOS_LISTA';
export const COMUNICADOS_LISTA_PROGRESSO = 'COMUNICADOS_LISTA_PROGRESSO';
export const COMUNICADOS_LISTA_ERRO = 'COMUNICADOS_LISTA_ERRO';
//Audências
export const AUDIENCIAS_LISTA = 'AUDIENCIAS_LISTA';
export const AUDIENCIAS_LISTA_PROGRESSO = 'AUDIENCIAS_LISTA_PROGRESSO';
export const AUDIENCIAS_LISTA_ERRO = 'AUDIENCIAS_LISTA_ERRO';
//Perfil 
export const PERFIL_PROGRESSO_SALVAR = 'PERFIL_PROGRESSO_SALVAR';
export const PERFIL_PROGRESSO_DADOS = 'PERFIL_PROGRESSO_DADOS';
export const PERFIL_ERRO = 'PERFIL_ERRO';
export const PERFIL_DADOS_SUCESSO = 'PERFIL_DADOS_SUCESSO';
export const PERFIL_SALVAR_SUCESSO = 'PERFIL_SALVAR_SUCESSO';
export const PERFIL_SALVAR_ERRO = 'PERFIL_SALVAR_ERRO';
export const PERFIL_SET_CELULAR = 'PERFIL_SET_CELULAR';
export const PERFIL_SET_TELEFONE = 'PERFIL_SET_TELEFONE';
export const PERFIL_SET_EMAIL = 'PERFIL_SET_EMAIL';
export const PERFIL_SET_CEP = 'PERFIL_SET_CEP';
export const PERFIL_SET_ENDERECO = 'PERFIL_SET_ENDERECO';
export const PERFIL_SET_NUMERO = 'PERFIL_SET_NUMERO';
export const PERFIL_SET_COMPLEMENTO = 'PERFIL_SET_COMPLEMENTO';
export const PERFIL_SET_BAIRRO = 'PERFIL_SET_BAIRRO';
export const PERFIL_SET_CIDADE = 'PERFIL_SET_CIDADE';
//Escala
export const ESCALA_PROGRESSO = 'ESCALA_PROGRESSO';
export const ESCALA_SUCESSO = 'ESCALA_SUCESSO';
export const ESCALA_ERRO = 'ESCALA_ERRO';
export const ESCALA_ADD_ESCALA_DATA = 'ESCALA_ADD_ESCALA_DATA';
export const ESCALA_PROGRESSO_REFRESH = 'ESCALA_PROGRESSO_REFRESH';
export const ESCALA_PROGRESSO_REFRESH_FIM = 'ESCALA_PROGRESSO_REFRESH_FIM';
//Gerar Escala
export const ESCALA_GERAR_SET_INICIAL = 'ESCALA_GERAR_SET_INICIAL';
export const ESCALA_GERAR_SET_FINAL = 'ESCALA_GERAR_SET_FINAL';
export const ESCALA_GERAR_SET_SABADO = 'ESCALA_GERAR_SET_SABADO';
export const ESCALA_GERAR_SET_DOMINGO = 'ESCALA_GERAR_SET_DOMINGO';
export const ESCALA_GERAR_SET_TIPO = 'ESCALA_GERAR_SET_TIPO';
export const ESCALA_GERAR_SET_HORARIO = 'ESCALA_GERAR_SET_HORARIO';
export const ESCALA_GERAR_SET_LOCAL = 'ESCALA_GERAR_SET_LOCAL';
export const ESCALA_GERAR_SET_OBSERVACAO = 'ESCALA_GERAR_SET_OBSERVACAO';
export const ESCALA_GERAR_HORARIOS = 'ESCALA_GERAR_HORARIOS';
export const ESCALA_GERAR_HORARIOS_SUCESSO = 'ESCALA_GERAR_HORARIOS_SUCESSO';
export const ESCALA_GERAR_HORARIOS_ERRO = 'ESCALA_GERAR_HORARIOS_ERRO';
export const ESCALA_GERAR_TIPOS = 'ESCALA_GERAR_TIPOS';
export const ESCALA_GERAR_TIPOS_SUCESSO = 'ESCALA_GERAR_TIPOS_SUCESSO';
export const ESCALA_GERAR_TIPOS_ERRO = 'ESCALA_GERAR_TIPOS_ERRO';
export const ESCALA_GERAR_ERRO = 'ESCALA_GERAR_ERRO';
export const ESCALA_GERAR_SUCESSO = 'ESCALA_GERAR_SUCESSO';
export const ESCALA_GERAR_PROGRESSO = 'ESCALA_GERAR_PROGRESSO';
export const ESCALA_GERAR_PROGRESSO_HORARIOS = 'ESCALA_GERAR_PROGRESSO_HORARIOS';
export const ESCALA_GERAR_PROGRESSO_TIPOS = 'ESCALA_GERAR_PROGRESSO_TIPOS';
